### ISSUE TITLE
demo: Show a before/after comparison

### ISSUE THREAD

**Issue by yashshah1** [fregante/fit-textarea#13]
Currently, the [demo website](https://fregante.github.io/fit-textarea/) only shows how using a `textarea` with `fit-textarea` will look like. Possibly add a toggle switch so the difference is evidently visible?

**Comment by fregante** [comment]
I don't think it's something that can be easily shown like that. At first load, the only thing that would change is that a textarea would be shorter than the other one.

The demo invites you to type something in the field, which is when the module comes into play.
