### ISSUE TITLE
Manual resizing issue

### ISSUE THREAD

**Issue by chrisblossom** [fregante/fit-textarea#9]
If you manually resize the text window (github comments) and interact with the textbox, the textbox automatically resizes to the original size. If I manually resize the box I not want it to be automatically resized back to the previous size.

![2019-07-16 11 19 52](https://user-images.githubusercontent.com/1595871/61319256-b9d55680-a7bb-11e9-94b9-f52be55e1b6b.gif)

**Comment by bfred-it** [comment]
That’s a good one. Manual resizing affects the same CSS property (`height`) so to fix this I should probably use `min-height` instead
